# -*- coding: utf-8 -*-
"""Discount.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D2XNgGX7LvgrbDXBYn8zfvVEqG1FVCep
"""

def calculate_discount(price, discount_percent):
  """
  Calculates the final price after applying a discount, with a minimum discount of 20%.

  Args:
      price: The original price of the item.
      discount_percent: The discount percentage (0 to 100).

  Returns:
      The final price after applying the discount, or the original price if the discount is less than 20%.
  """

  if discount_percent >= 20:
    discount = price * discount_percent / 100
    final_price = price - discount
  else:
    final_price = price

  return final_price

# Assuming the item price is always 1000
item_price = 1000

# Get user input for discount percentage
discount_percentage = float(input("Enter the discount percentage (0 to 100): "))

# Calculate and print the final price
final_price = calculate_discount(item_price, discount_percentage)
print(f"The final price of the ${item_price:.2f} item after applying the discount is: ${final_price:.2f}")

def calculate_discount(price, discount_percent):
  """
  Calculates the final price after applying a discount, with a minimum discount of 20%.

  Args:
      price: The original price of the item.
      discount_percent: The discount percentage (0 to 100).

  Returns:
      The final price after applying the discount, or the original price if the discount is less than 20%.
  """

  if discount_percent >= 20:
    discount = price * discount_percent / 100
    final_price = price - discount
  else:
    final_price = price

  return final_price

# Get user input for price and discount percentage
original_price = float(input("Enter the original price of the item: "))
discount_percentage = float(input("Enter the discount percentage (0 to 100): "))

# Calculate and print the final price
final_price = calculate_discount(original_price, discount_percentage)
print(f"The final price after applying the discount is: ${final_price:.2f}")

